kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: guestbook
subjects:
- kind: ServiceAccount
  name: guestbook
roleRef:
  kind: Role
  name: guestbook
  apiGroup: rbac.authorization.k8s.io
